/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.commons.jelly;

/**
 * <p>
 * A {@code JellyTagException} is an exception generated by a Tag implementation.
 * </p>
 */

public class JellyTagException extends JellyException {

    public JellyTagException() {
    }

    public JellyTagException(final String message) {
        super(message);
    }

    public JellyTagException(final String reason, final String fileName, final String elementName, final int columnNumber, final int lineNumber) {
        super(reason, fileName, elementName, columnNumber, lineNumber);
    }

    public JellyTagException(final String message, final Throwable cause) {
        super(message, cause);
    }

    public JellyTagException(final String reason, final Throwable cause, final String fileName, final String elementName, final int columnNumber, final int lineNumber) {
        super(reason, cause, fileName, elementName, columnNumber, lineNumber);
    }

    public JellyTagException(final Throwable cause) {
        super(cause);
    }

    public JellyTagException(final Throwable cause, final String fileName, final String elementName, final int columnNumber, final int lineNumber) {
        super(cause, fileName, elementName, columnNumber, lineNumber);
    }

}
